Models/EnumStatusTarefa.cs
namespace Trilha_Net_MVC_Desafio.Models
{
    public enum EnumStatusTarefa
        {
            Pendente,
            Finalizado
        }
}

Models/ErrorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Trilha_Net_MVC_Desafio.Models
{

    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Tarefa.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Trilha_Net_MVC_Desafio.Models
{
    public class Tarefa
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public DateTime Data { get; set; }
        public EnumStatusTarefa Status { get; set; }

    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using  Trilha_Net_MVC_Desafio.Models;

namespace  Trilha_Net_MVC_Desafio.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/TarefaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Trilha_Net_MVC_Desafio.Context;
using Trilha_Net_MVC_Desafio.Models;

namespace Trilha_Net_MVC_Desafio.Controllers
{
    public class TarefaController : Controller
    {
        private readonly OrganizadorContext _context;

        public TarefaController(OrganizadorContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var tarefas = _context.Tarefas.ToList();
            return View(tarefas);
        }
        public IActionResult Criar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Criar(Tarefa tarefa)
        {
            if (ModelState.IsValid)
            {
                _context.Tarefas.Add(tarefa);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(tarefa);
        }
        public IActionResult Editar(int id)
        {
            //Buscar no banco
            var Tarefa = _context.Tarefas.Find(id);
            if (Tarefa == null)
                return RedirectToAction(nameof(Index));
            return View(Tarefa);
        }

        [HttpPost]
        public IActionResult Editar(Tarefa Tarefa)
        {
            var TarefaBanco = _context.Tarefas.Find(Tarefa.Id);

            TarefaBanco.Titulo = Tarefa.Titulo;
            TarefaBanco.Descricao = Tarefa.Descricao;
            TarefaBanco.Data = Tarefa.Data;
            TarefaBanco.Status = Tarefa.Status;

            _context.Tarefas.Update(TarefaBanco);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Detalhes(int id)
        {
            var Tarefa = _context.Tarefas.Find(id);

            if (Tarefa == null)
                return RedirectToAction(nameof(Index));

            return View(Tarefa);
        }
        public IActionResult Deletar(int id)
        {
            //Buscar no banco
            var Tarefa = _context.Tarefas.Find(id);

            if (Tarefa == null)
                return RedirectToAction(nameof(Index));
            return View(Tarefa);
        }

        [HttpPost]
        public IActionResult Deletar(Tarefa Tarefa)
        {
            var TarefaBanco = _context.Tarefas.Find(Tarefa.Id);

            _context.Tarefas.Remove(TarefaBanco);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trilha_Net_MVC_Desafio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Trilha_Net_MVC_Desafio.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trilha_Net_MVC_Desafio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item"></li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefa" asp-action="Index">Tarefas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Trilha_Net_MVC_Desafio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Tarefa/Criar.cshtml
@model Trilha_Net_MVC_Desafio.Models.Tarefa

@{
    ViewData["Title"] = "Criar nova Tarefa";
}

<h1>Criar nova Tarefa</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Criar">
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" asp-items="Html.GetEnumSelectList<EnumStatusTarefa>()" class="form-control"></select>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
</hr>
<br>
<div>
    <a asp-action="Index">Voltar</a>
</div>

Views/Tarefa/Deletar.cshtml
@model Trilha_Net_MVC_Desafio.Models.Tarefa

@{
    ViewData["Title"] = "Deletar Tarefa";
}

<h1 style="color: red;">Deseja realmente deletar esta tarefa?</h1>

</hr>
<th>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>

<form asp-action = "Deletar">
    <input type="submit" value="Deletar" class="btn btn-danger">
</form>
<br>
<a asp-action="Index">Voltar</a>

Views/Tarefa/Detalhes.cshtml
@model Trilha_Net_MVC_Desafio.Models.Tarefa


@{
    ViewData["Title"] = "Detalhes do contato";
}

<h1>Detalhes</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Titulo)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Titulo)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Descricao)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Descricao)
        </dt>
        <dt class="col-sm-2"></dt>
            @Html.DisplayNameFor(x => x.Data)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Data)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Status)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Status)
        </dt>
    </dl>
</div>
<a asp-action="Deletar" asp-route-id="@Model.Id">Deletar</a> | 
<a asp-action="Index">Voltar</a>

Views/Tarefa/Editar.cshtml
@model Trilha_Net_MVC_Desafio.Models.Tarefa

@{
    ViewData["Title"] = "Editor de Tarefa";
}

<h1>Editar de Tarefa</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" asp-items="Html.GetEnumSelectList<EnumStatusTarefa>()" class="form-control"></select>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
</hr>
<br>
<div>
    <a asp-action="Index">Voltar</a>
</div>

Views/Tarefa/Index.cshtml
@model IEnumerable<Trilha_Net_MVC_Desafio.Models.Tarefa>

@{
    ViewData["Title"] = "Listagem de tarefas";
}

<h2>Tarefas</h2>

<p>
    <a asp-action="Criar">Nova Tarefa</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Descricao)
                </td>    
                <td>
                    @Html.DisplayFor(model => item.Data)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Status)
                </td>
                <td>
                    <a asp-action="Editar" asp-route-id="@item.Id">Editar</a> |
                    <a asp-action="Detalhes" asp-route-id="@item.Id">Detalhes</a> |
                    <a asp-action="Deletar" asp-route-id="@item.Id">Deletar</a>
                </td>
            </tr>
        }
    </tbody>
</table>